/**
 * Observability Integration
 * 
 * PHASE 4: Observability, Attribution & Replay
 * 
 * Integrates observability hooks into governance system.
 * This module adds logging WITHOUT modifying execution logic.
 */

import { EventLog, EventType, CapitalCheckEvent, RegimeCheckEvent, PermissionCheckEvent, RiskCheckEvent, TradeExecutedEvent, TradeBlockedEvent, SystemModeChangeEvent, StrategyStateChangeEvent, RegimeDetectedEvent } from './event_log';
import { CapitalGateResult } from '../capital/capital_gate';
import { RegimeGateResult } from '../regime_gate';
import { PermissionResult } from '../permission_gate';
import { TradeRequest, TradeResult } from '../../src/services/riskGovernor';
import { MarketRegime } from '../regime_detector';

/**
 * Observability Hooks
 * 
 * Adds event logging to governance operations without modifying logic.
 */
export class ObservabilityHooks {
  private eventLog: EventLog;

  constructor(eventLog: EventLog) {
    this.eventLog = eventLog;
  }

  /**
   * Log capital check event
   */
  logCapitalCheck(
    strategyId: string,
    tradeValue: number,
    result: CapitalGateResult,
    systemMode: string
  ): void {
    const event: CapitalCheckEvent = {
      eventId: '', // Will be generated by eventLog
      timestamp: new Date(),
      eventType: EventType.CAPITAL_CHECK,
      strategyId,
      systemMode,
      requestedAmount: tradeValue,
      allocatedCapital: result.allocatedCapital,
      allowed: result.allowed,
      reason: result.reason || 'Capital check completed'
    };

    this.eventLog.append(event);
  }

  /**
   * Log regime check event
   */
  logRegimeCheck(
    strategyId: string,
    symbol: string,
    result: RegimeGateResult,
    systemMode: string
  ): void {
    const event: RegimeCheckEvent = {
      eventId: '',
      timestamp: new Date(),
      eventType: EventType.REGIME_CHECK,
      strategyId,
      systemMode,
      currentRegime: result.regime || 'UNKNOWN',
      allowedRegimes: [], // Would need to get from strategy metadata
      allowed: result.allowed,
      reason: result.reason || 'Regime check completed'
    };

    this.eventLog.append(event);
  }

  /**
   * Log permission check event
   */
  logPermissionCheck(
    strategyId: string,
    result: PermissionResult,
    systemMode: string
  ): void {
    const event: PermissionCheckEvent = {
      eventId: '',
      timestamp: new Date(),
      eventType: EventType.PERMISSION_CHECK,
      strategyId,
      systemMode,
      tradingAllowed: result.allowed,
      allowed: result.allowed,
      reason: result.reason || 'Permission check completed'
    };

    this.eventLog.append(event);
  }

  /**
   * Log risk check event
   */
  logRiskCheck(
    strategyId: string,
    allowed: boolean,
    riskState: string,
    drawdown: number,
    reason: string,
    systemMode: string
  ): void {
    const event: RiskCheckEvent = {
      eventId: '',
      timestamp: new Date(),
      eventType: EventType.RISK_CHECK,
      strategyId,
      systemMode,
      riskState,
      drawdown,
      allowed,
      reason
    };

    this.eventLog.append(event);
  }

  /**
   * Log trade executed event
   */
  logTradeExecuted(
    request: TradeRequest,
    result: TradeResult,
    systemMode: string,
    regime?: MarketRegime,
    regimeConfidence?: number
  ): void {
    const event: TradeExecutedEvent = {
      eventId: '',
      timestamp: new Date(),
      eventType: EventType.TRADE_EXECUTED,
      strategyId: request.strategy,
      systemMode,
      regime: regime?.toString(),
      regimeConfidence,
      pair: request.pair,
      action: request.action,
      amount: request.amount,
      price: request.price,
      orderId: result.orderId,
      executedValue: result.executedValue || request.estimatedValue,
      reason: 'Trade executed successfully',
      metadata: {
        pnl: result.pnl,
        slippage: 0 // Would be calculated if available
      }
    };

    this.eventLog.append(event);
  }

  /**
   * Log trade blocked event
   */
  logTradeBlocked(
    request: TradeRequest,
    blockingLayer: 'CAPITAL' | 'REGIME' | 'PERMISSION' | 'RISK',
    reason: string,
    systemMode: string,
    regime?: MarketRegime,
    regimeConfidence?: number
  ): void {
    const event: TradeBlockedEvent = {
      eventId: '',
      timestamp: new Date(),
      eventType: EventType.TRADE_BLOCKED,
      strategyId: request.strategy,
      systemMode,
      regime: regime?.toString(),
      regimeConfidence,
      pair: request.pair,
      blockingLayer,
      reason
    };

    this.eventLog.append(event);
  }

  /**
   * Log system mode change
   */
  logSystemModeChange(
    previousMode: string,
    newMode: string,
    reason: string
  ): void {
    const event: SystemModeChangeEvent = {
      eventId: '',
      timestamp: new Date(),
      eventType: EventType.SYSTEM_MODE_CHANGE,
      previousMode,
      newMode,
      reason
    };

    this.eventLog.append(event);
  }

  /**
   * Log strategy state change
   */
  logStrategyStateChange(
    strategyId: string,
    previousState: string,
    newState: string,
    reason: string,
    systemMode: string
  ): void {
    const event: StrategyStateChangeEvent = {
      eventId: '',
      timestamp: new Date(),
      eventType: EventType.STRATEGY_STATE_CHANGE,
      strategyId,
      systemMode,
      previousState,
      newState,
      reason
    };

    this.eventLog.append(event);
  }

  /**
   * Log regime detection
   */
  logRegimeDetected(
    symbol: string,
    regime: MarketRegime,
    confidence: number,
    metrics: {
      realizedVolatility: number;
      volatilityExpansion: number;
      trendStrength: number;
      correlationStability: number;
    },
    systemMode: string
  ): void {
    const event: RegimeDetectedEvent = {
      eventId: '',
      timestamp: new Date(),
      eventType: EventType.REGIME_DETECTED,
      systemMode,
      symbol,
      regime: regime.toString(),
      confidence,
      metrics,
      reason: `Regime detected: ${regime} (${(confidence * 100).toFixed(0)}% confidence)`
    };

    this.eventLog.append(event);
  }
}

